import { GLITCHLESS_CUTOFFS, SHEET_NAMES } from "./consts.js";

export const CATEGORIES = [
  {
    "name": "All Advancements",
    "id": "xk9gz16d",
    "sheetName": SHEET_NAMES.AA,
    "longTimes": true,
    "cutoffs": null,
    "versionId": "789je4qn",
    "seedTypeId": "p853vv0n",
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "All Advancements Co-op",
    "id": "xd114pzd",
    "sheetName": SHEET_NAMES.AA,
    "longTimes": true,
    "cutoffs": null,
    "versionId": "wl314d98",
    "seedTypeId": "2lg3x13n",
    "playerCountId": "789xmd68",
    "glitchedTypeId": "",
  },
  {
    "name": "All Achievements",
    "id": "wk63eek1",
    "sheetName": SHEET_NAMES.AA,
    "longTimes": true,
    "cutoffs": null,
    "versionId": "0nw2y7xn",
    "seedTypeId": "38do09zl",
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "Any% Glitchless",
    "id": "mkeyl926",
    "sheetName": SHEET_NAMES.RSG_116,
    "longTimes": false,
    "cutoffs": GLITCHLESS_CUTOFFS,
    "versionId": "wl33kewl",
    "versionFilter": "4qye4731", // 1.16-1.19
    "seedTypeId": "r8rg67rn",
    "seedTypeFilter": "21d4zvp1", // Random Seed
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "Any% Glitchless",
    "id": "mkeyl926",
    "sheetName": SHEET_NAMES.RSG,
    "longTimes": false,
    "cutoffs": GLITCHLESS_CUTOFFS,
    "versionId": "wl33kewl",
    "seedTypeId": "r8rg67rn",
    "seedTypeFilter": "21d4zvp1", // Random Seed
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "Any% Glitchless",
    "id": "mkeyl926",
    "sheetName": SHEET_NAMES.SSG,
    "longTimes": false,
    "cutoffs": GLITCHLESS_CUTOFFS,
    "versionId": "wl33kewl",
    "seedTypeId": "r8rg67rn",
    "seedTypeFilter": "klrzpjo1", // Set Seed
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "Any% Glitchless Co-op", // x=zd301qed-rn1p34dn.5lm7wvjl-68kd9yql.rqvojn6l-68k5jz82.jqz6vmm1
    "id": "zd301qed",
    "sheetName": SHEET_NAMES.COOP,
    "longTimes": false,
    "cutoffs": null,
    "versionId": "68kd9yql",
    "seedTypeId": "rn1p34dn",
    "playerCountId": "68k5jz82",
    "glitchedTypeId": "",
  },
  {
    "name": "Any%",
    "id": "wkpn0vdr",
    "sheetName": SHEET_NAMES.GLITCHED_PEACEFUL,
    "longTimes": false,
    "cutoffs": null,
    "versionId": "wlexoyr8",
    "seedTypeId": "2lgzk1o8",
    "playerCountId": "",
    "glitchedTypeId": "68k15rkl",
  },
  {
    "name": "Any% Glitchless (Peaceful)",
    "id": "9d86nz62",
    "sheetName": SHEET_NAMES.GLITCHED_PEACEFUL,
    "longTimes": false,
    "cutoffs": null,
    "versionId": "ylqmmrvn",
    "seedTypeId": "wle63kx8",
    "playerCountId": "",
    "glitchedTypeId": "",
  },
  {
    "name": "Any% (Peaceful)",
    "id": "xd1qp728",
    "sheetName": SHEET_NAMES.GLITCHED_PEACEFUL,
    "longTimes": false,
    "cutoffs": null,
    "versionId": "gnxvv7gl",
    "seedTypeId": "wl36vd6l",
    "playerCountId": "",
    "glitchedTypeId": "",
  }
]