// import { GoogleSpreadsheet } from 'google-spreadsheet';
// import { JWT } from 'google-auth-library';

// import creds from './credentials.json' with { type: "json" };

// // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
// const serviceAccountAuth = new JWT({
//   // env var values here are copied from service account credentials generated by google
//   // see "Authentication" section in docs for more info
//   email: creds.client_email,
//   key: creds.private_key,
//   scopes: [
//     'https://www.googleapis.com/auth/spreadsheets',
//     'https://www.googleapis.com/auth/drive.file',],
// });

// const doc = new GoogleSpreadsheet('1qsPHFXee0SB0Pc8KYxLWa-u18xjFoAymzu4ALyI17gs', serviceAccountAuth);

// export async function appendToSheet(data) {
//   await doc.loadInfo(); // loads document properties and worksheets
//   // const sheet = await doc.addSheet({ headerValues: ['name', 'email'] });
//   const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
//   console.log(sheet.title);
//   console.log(sheet.rowCount);
  
//   // read rows
//   const rows = await sheet.getRows(); // can pass in { limit, offset }
  
//   // append rows
//   const larryRow = await sheet.addRow({ Name: 'Larry Page', Time: 'larry@google.com' });
//   // const moreRows = await sheet.addRows([
//   //   { name: 'Sergey Brin', email: 'sergey@google.com' },
//   //   { name: 'Eric Schmidt', email: 'eric@google.com' },
//   // ]);
// }

// appendToSheet()

// console.log(doc.title);
// await doc.updateProperties({ title: 'renamed doc' });

// const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
// console.log(sheet.title);
// console.log(sheet.rowCount);

// adding / removing sheets
// const newSheet = await doc.addSheet({ title: 'another sheet' });
// await newSheet.delete();

import express from 'express';
const app = express()

app.use(express.static('public'));
app.get('/', async (req, res) => {
  // appendToSheet();
  res.send('Hello World')}
);

const PORT = process.env.PORT || 8080;
app.listen(PORT, () => {
  console.log(
    `Hello from Cloud Run! The container started successfully and is listening for HTTP requests on ${PORT}`
  );
});
